### ISSUE TITLE
Running a migration with json field alters json type to text in PostgreSQL

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/migrations#10]
Here's my schema:

```
/**
 * @Cycle\Entity(
 *     table="table"
 * )
 * @Cycle\Table(
 *     columns={
 *      "id": @Cycle\Column(type="bigPrimary"),
 *      "data": @Cycle\Column(type="json", nullable=true),
 *     }
 * )
 */
class Model
{
    public ?string $data = null;
}
```

Running `cycle:migrate` on already existing table will create a migration that looks like:

```
$this->table('table')
    ->alterColumn('data', 'json', [
        'nullable' => true,
        'default'  => null
    ])
    ->update();
```

Already existing PostgreSQL table's DDL has no default:

```
CREATE TABLE table (
    id BIGSERIAL PRIMARY KEY,
    data json
);
```

Cannot confirm, but this might only be happening with `json` fields.

**Comment by wolfy-j** [comment]
This is the expected behavior. We are not planning to change type mapping going forward but instead use the new types. Mapping to native JSON was a mistake since this type behave differently in PG.

**Comment by rauanmayemir** [comment]
What's the resolution on this?

**Comment by wolfy-j** [comment]
This is the expected behavior. The default won't be set for JSON. I thought we discussed that in Discord. Didn't we?

**Comment by rauanmayemir** [comment]
It's not about the default, but the fact that spiral is altering `json` type to `text`. I suspect that's the reason why migrations are being created in the first place.

Basically, I can no longer use `json` type, because it will be altered to `text` in subsequent migrations.
