### ISSUE TITLE
Проблема с уникальностью названий миграций

### ISSUE THREAD

**Issue by butschster** [spiral/migrations#13]
Всем привет.
Прежде всего спасибо за отличный инструмент!

**А теперь к проблеме:**
Существует ситуация, когда миграции перестают быть уникальными, например:
1. Я изменяю в Entity, допустим поле `date`, делаю его nullable
```php
/** @ORM\Column(type="date", nullable=true) */
protected $date = null;
```
2. Создаю миграцию
```
20200519.090522_0_0_default_change_users_alter_date_change_users_alter_date.php
```
3. Меняю это поле обратно
```php
/** @ORM\Column(type="date") */
protected $date = null;
```
2. Создаю миграцию
```
20200521.090522_0_0_default_change_users_alter_date_change_users_alter_date.php
```

Когда мигратор записывает исполненную миграцию в БД, то в этот момент отбрасывается timestamp и chunk, т.е. вот эту часть `20200521.090522_0_` и мы получаем два полностью идентичных названия миграций, которые должны записаться в БД и это приводит к ошибке.

Моде предложение, добавить timestamp к имени миграции, это позволит сделать названия действительно уникальными.

**P.S.** Единственный огромнейший недостаток ваших инструментов в том, что все классы у вас помечены как `final`, что приводит к проблеме, когда у меня есть желание подправить немного поведение под свои задачи, то мне приходится копировать весь код, вместо наследования ваших классов и переопределения нужных методов.

**Comment by wolfy-j** [comment]
Привет, кажется проблема вылезла как только мы начали именовать миграции автоматически.
На следующей неделе поправим, если не будет PR до этого. Спасибо за репорт.

На тему `final` - отсутствие final дает пользователям возможность менять поведение **внутреннего** АПИ без оглядки на остальных пользователей. Учитывая что у нас 80+ пакетов которые нужно мейнтейнить, поддержка так-же внутреннего АПИ потребует на несколько порядков больше времени. Считайте что final это приглашение к диалогу. В любом случае, почти все компоненты имеют интерфейсы.

**Comment by SerafimArts** [comment]
Done https://github.com/spiral/migrations/pull/17
