### ISSUE TITLE
Error "1071 Specified key was too long; max key length is 767 bytes" on create migration table

### ISSUE THREAD

**Issue by vjik** [spiral/migrations#18]
`Exception 'Spiral\Database\Exception\HandlerException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes'`

Appear in MySQL 5.6 with utf8mb4.

Problem here: https://github.com/spiral/migrations/blob/master/src/Migrator.php#L101

Maybe replace 255 to 191 ?

**Comment by SerafimArts** [comment]
@wolfy-j yes, its correct decision. For this encoding the maximum length is limited to 191 bytes. However, it makes sense to do something with this: https://github.com/spiral/database/blob/master/src/Schema/AbstractColumn.php#L612
