### ISSUE TITLE
Doesn't work migration with option default

### ISSUE THREAD

**Issue by Eugentis** [spiral/migrations#6]
Working with existing table I've detected that default value wasn't changed after migration.
In initial table we have column like:
user_id    int    default 0   not null,

I need to change it to nullable with default null value. In migration:
```
$this->table('record')
            ->alterColumn('user_id', 'integer', [
                'nullable' => true,
                'default' => null
            ])
        ->update();
```

After migration default value for this column was not changed:
user_id    int    default 0    null,

used driver is MySQL

**Comment by wolfy-j** [comment]
Can not reproduce :(
