### ISSUE TITLE
`PDO::ATTR_STRINGIFY_FETCHES` breaks migrations

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/migrations#7]
I have `PDO::ATTR_STRINGIFY_FETCHES => true` set for Postgres driver and it works fine.
However, `cycle:migrate` fails with:
```
 [TypeError]
 Return value of Spiral\Database\Schema\AbstractColumn::getSize() must be of the type int, string returned
```

This is because a string column's size is returned as '255'.

**Comment by wolfy-j** [comment]
Fixed in `spiral/database v2.7.1`
