### ISSUE TITLE
Columns keep being altered

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/migrations#9]
There is a regression in spiral that adds noise to the migrations. For any type of column there is a pre-set nulled default:

```
->addColumn('column', 'string', [
    'nullable' => false,
    'default'  => null,
    'size'     => 255
])
```

And on each `cycle:migrate` spiral keeps altering the columns with the same info:

```
->alterColumn('column', 'string', [
    'nullable' => false,
    'default'  => null,
    'size'     => 255
])
```

**Comment by wolfy-j** [comment]
Can you specify the driver and database versions? Any way to reproduce?

**Comment by rauanmayemir** [comment]
Was able to reproduce it, it's `PDO::ATTR_STRINGIFY_FETCHES` again. If turned on, spiral can't properly sync changes.

**Comment by rauanmayemir** [comment]
Should we have it on for tests?
E.g from Laravel, I remember SQLite often returning strings in place of integers without any PDO option changes. This way, we could make sure we first cast our values correctly.

**Comment by wolfy-j** [comment]
Yes please, if you can add a test which demonstrates the issue it would be much easier for us to fix.

**Comment by rauanmayemir** [comment]
I'll try to take care of this myself.

**Comment by wolfy-j** [comment]
Thank you!
